name: task_master
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.28.0
  smooth_page_indicator: 
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/logos/
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/others/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
