// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyU3vWflcL8NNnLl01eFKXPcWpYzyqZ2c',
    appId: '1:584588186518:web:a30533e0f08d30c43183b7',
    messagingSenderId: '584588186518',
    projectId: 'task-manager-26b5d',
    authDomain: 'task-manager-26b5d.firebaseapp.com',
    storageBucket: 'task-manager-26b5d.appspot.com',
    measurementId: 'G-QWYWB2YRRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgWfgMrHi25F1QdjqW4RaGCDgAuwQvyE',
    appId: '1:584588186518:android:dd8c2165a41dfb863183b7',
    messagingSenderId: '584588186518',
    projectId: 'task-manager-26b5d',
    storageBucket: 'task-manager-26b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHZBqmAP_iJwPiqdu_NSHxWThcS9i45s',
    appId: '1:584588186518:ios:ae0d16a9a616c9b03183b7',
    messagingSenderId: '584588186518',
    projectId: 'task-manager-26b5d',
    storageBucket: 'task-manager-26b5d.appspot.com',
    iosBundleId: 'com.example.taskMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhHZBqmAP_iJwPiqdu_NSHxWThcS9i45s',
    appId: '1:584588186518:ios:2a3505ee5a8f58083183b7',
    messagingSenderId: '584588186518',
    projectId: 'task-manager-26b5d',
    storageBucket: 'task-manager-26b5d.appspot.com',
    iosBundleId: 'com.example.taskMaster.RunnerTests',
  );
}
